[2024-04-06T14:46:39.125+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/scripts/_etl.py
[2024-04-06T14:46:39.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/scripts/_etl.py for tasks to queue
[2024-04-06T14:46:39.128+0000] {logging_mixin.py:188} INFO - [2024-04-06T14:46:39.128+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/scripts/_etl.py
[2024-04-06T14:46:39.154+0000] {logging_mixin.py:188} INFO - [2024-04-06T14:46:39.139+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/scripts/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/scripts/_etl.py", line 4, in <module>
    from python.liquidity_aggregator import run_pipeline
ModuleNotFoundError: No module named 'python'
[2024-04-06T14:46:39.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/scripts/_etl.py
[2024-04-06T14:46:39.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/scripts/_etl.py took 0.127 seconds
